"""Exact approved names only; enumeration does not perform strategy actions."""

from enum import StrEnum


class ContextDataClassification(StrEnum):
    NO_TRADE_15M = "NO_TRADE_15M"
    INVALID_15M_DATA = "INVALID_15M_DATA"


class HistoryClassification(StrEnum):
    NONEXISTENT_HISTORY = "NONEXISTENT_HISTORY"
    MISSING_OR_INVALID_HISTORY = "MISSING_OR_INVALID_HISTORY"


class SetupTermination(StrEnum):
    INVALIDATED = "INVALIDATED"
    EXPIRED = "EXPIRED"
    CONSUMED = "CONSUMED"


class ReasonCode(StrEnum):
    DATA_GAP = "DATA_GAP"
    INVALID_DATA = "INVALID_DATA"
    RVOL_BASELINE_ZERO = "RVOL_BASELINE_ZERO"
    MARKET_CAP_DATA_UNAVAILABLE = "MARKET_CAP_DATA_UNAVAILABLE"
    INSUFFICIENT_ADV_HISTORY = "INSUFFICIENT_ADV_HISTORY"
    INSUFFICIENT_ADR20_HISTORY = "INSUFFICIENT_ADR20_HISTORY"
    ADR20_DATA_UNAVAILABLE = "ADR20_DATA_UNAVAILABLE"
    DYNAMIC_PRICE_ABOVE_MAX = "DYNAMIC_PRICE_ABOVE_MAX"
    DYNAMIC_DAILY_CHANGE_BELOW_MIN = "DYNAMIC_DAILY_CHANGE_BELOW_MIN"
    DYNAMIC_MULTIPLE_ELIGIBILITY_FAILURES = "DYNAMIC_MULTIPLE_ELIGIBILITY_FAILURES"
    ENTRY_DYNAMIC_PRICE_ABOVE_MAX = "ENTRY_DYNAMIC_PRICE_ABOVE_MAX"
    ENTRY_DYNAMIC_DAILY_CHANGE_BELOW_MIN = "ENTRY_DYNAMIC_DAILY_CHANGE_BELOW_MIN"
    ENTRY_DYNAMIC_MULTIPLE_ELIGIBILITY_FAILURES = "ENTRY_DYNAMIC_MULTIPLE_ELIGIBILITY_FAILURES"
    ENTRY_NO_TRADE = "ENTRY_NO_TRADE"
    ENTRY_DATA_MISSING = "ENTRY_DATA_MISSING"
    ENTRY_DATA_INVALID = "ENTRY_DATA_INVALID"
    ENTRY_OPEN_ABOVE_MAX = "ENTRY_OPEN_ABOVE_MAX"
    ENTRY_OPEN_AT_OR_BELOW_B = "ENTRY_OPEN_AT_OR_BELOW_B"
    ENTRY_TIME_RESTRICTION = "ENTRY_TIME_RESTRICTION"
    ENTRY_TICK_SIZE_UNAVAILABLE = "ENTRY_TICK_SIZE_UNAVAILABLE"
    ENTRY_TARGET_TICK_SIZE_UNAVAILABLE = "ENTRY_TARGET_TICK_SIZE_UNAVAILABLE"
    ENTRY_15M_STRUCTURE_BEARISH = "ENTRY_15M_STRUCTURE_BEARISH"
    ENTRY_INSUFFICIENT_15M_CONTEXT = "ENTRY_INSUFFICIENT_15M_CONTEXT"
    ENTRY_15M_CONTEXT_NO_TRADE = "ENTRY_15M_CONTEXT_NO_TRADE"
    ENTRY_15M_DATA_UNAVAILABLE = "ENTRY_15M_DATA_UNAVAILABLE"
    ENTRY_INSUFFICIENT_WEEKLY_HISTORY = "ENTRY_INSUFFICIENT_WEEKLY_HISTORY"
    ENTRY_WEEKLY_DATA_UNAVAILABLE = "ENTRY_WEEKLY_DATA_UNAVAILABLE"
    ENTRY_INSUFFICIENT_WEEKLY_ROOM = "ENTRY_INSUFFICIENT_WEEKLY_ROOM"
    NO_IDENTIFIED_WEEKLY_RESISTANCE = "NO_IDENTIFIED_WEEKLY_RESISTANCE"
    CORPORATE_ACTION_DATA_UNAVAILABLE = "CORPORATE_ACTION_DATA_UNAVAILABLE"
    INTRABAR_SEQUENCE_AMBIGUITY = "INTRABAR_SEQUENCE_AMBIGUITY"
    C_INVALIDATION_INTRABAR_AMBIGUITY = "C_INVALIDATION_INTRABAR_AMBIGUITY"
    SAME_BAR_2R_BREAKEVEN_AMBIGUITY = "SAME_BAR_2R_BREAKEVEN_AMBIGUITY"
    UNRESOLVED_EOD_NO_LIQUIDITY = "UNRESOLVED_EOD_NO_LIQUIDITY"


class RunStatus(StrEnum):
    INCOMPLETE_UNRESOLVED_EOD_LIQUIDITY = "INCOMPLETE_UNRESOLVED_EOD_LIQUIDITY"
    INCOMPLETE_TICK_SIZE_UNAVAILABLE_OPEN_POSITION = "INCOMPLETE_TICK_SIZE_UNAVAILABLE_OPEN_POSITION"

# Generic running/paused/complete labels are intentionally not invented here.
